In [1]:
import numpy as np
import numpy.linalg as la
from numpy.linalg import eig
from numpy.linalg import inv

import time

In [2]:
# diagonalization and power of a matrix
A = np.array([[4, 0, -2], [2, 5, 4], [0, 0, 5]])
A

array([[ 4,  0, -2],
       [ 2,  5,  4],
       [ 0,  0,  5]])

In [3]:
eig_val, eig_vec = eig(A)

In [4]:
eig_val

array([5., 4., 5.])

In [5]:
eig_vec

array([[ 0.        ,  0.4472136 , -0.89442719],
       [ 1.        , -0.89442719,  0.        ],
       [ 0.        ,  0.        ,  0.4472136 ]])

In [6]:
D = np.diag(eig_val)
D

array([[5., 0., 0.],
       [0., 4., 0.],
       [0., 0., 5.]])

In [7]:
V = eig_vec
V

array([[ 0.        ,  0.4472136 , -0.89442719],
       [ 1.        , -0.89442719,  0.        ],
       [ 0.        ,  0.        ,  0.4472136 ]])

In [8]:
V.dot(D).dot(la.inv(V))

array([[ 4.,  0., -2.],
       [ 2.,  5.,  4.],
       [ 0.,  0.,  5.]])

In [9]:
la.matrix_power(A,5)

array([[ 1024,     0, -4202],
       [ 4202,  3125,  8404],
       [    0,     0,  3125]])

In [10]:
D_power_5 = np.diag(eig_val**5)
D_power_5

array([[3125.,    0.,    0.],
       [   0., 1024.,    0.],
       [   0.,    0., 3125.]])

In [11]:
V.dot(D_power_5).dot(la.inv(V))

array([[ 1024.,     0., -4202.],
       [ 4202.,  3125.,  8404.],
       [    0.,     0.,  3125.]])

In [12]:
# create a matrix A
A = np.array([[4., 4, 2, 3, -2], [0, 1, -2, -2, 2], [6, 12, 11, 2, -4], [9, 20, 10, 10, -6], [15, 28, 14, 5, -3]])

A = A + A.T
A = A/np.expand_dims(np.sum(A, 1), axis = 1)
print (A)

# initialize parameters
x = np.random.rand(5)
n_times = 1000000

# perform matrix multiplications
y = x
start_time = time.time()
for i in range(0, n_times):
    y = A.dot(y)
end_time = time.time()
elapse_time = end_time - start_time
print (y)
print (elapse_time)

[[ 0.17777778  0.08888889  0.17777778  0.26666667  0.28888889]
 [ 0.0625      0.03125     0.15625     0.28125     0.46875   ]
 [ 0.12903226  0.16129032  0.35483871  0.19354839  0.16129032]
 [ 0.19672131  0.29508197  0.19672131  0.32786885 -0.01639344]
 [ 0.2826087   0.65217391  0.2173913  -0.02173913 -0.13043478]]
[0.67867964 0.67867964 0.67867964 0.67867964 0.67867964]
0.8730270862579346


In [13]:
eig_val, eig_vec = eig(A)
D = np.diag(eig_val)
V = eig_vec

# perform matrix multiplications using eigendecomposition
start_time = time.time()
y = V.dot((eig_val**n_times)*la.solve(V,x))
end_time = time.time()
elapse_time = end_time - start_time
print (y)
print (elapse_time)

[0.67867964 0.67867964 0.67867964 0.67867964 0.67867964]
0.00040149688720703125
